### Pega a lista de usuários cadastrados
http://localhost:3000/users

### Cadatra um usuário
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "email": "birutaibm@gmail.com",
  "password": "123456"
}

### Inicia uma nova seção (login)
POST http://localhost:3000/sessions HTTP/1.1
content-type: application/json

{
  "email": "birutaibm@gmail.com",
  "password": "123456"
}

### Pega a lista de ferramentas cadastradas
http://localhost:3000/tools

### Cadastra uma nova ferramenta
POST http://localhost:3000/tools HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTUxMTUyNzMsImV4cCI6MTU5NTExODg3Mywic3ViIjoiYmlydXRhaWJtQGdtYWlsLmNvbSJ9.P0Or5phYdlNdtGSCwRfgU85jPCOLhezUTOPxOHHwfPI

{
  "title": "hotel",
  "link": "https://github.com/typicode/hotel",
  "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
  "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
}

###
DELETE http://localhost:3000/tools/5f137ba781df261edf8098d2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTUxMTUyNzMsImV4cCI6MTU5NTExODg3Mywic3ViIjoiYmlydXRhaWJtQGdtYWlsLmNvbSJ9.P0Or5phYdlNdtGSCwRfgU85jPCOLhezUTOPxOHHwfPI
